### ISSUE TITLE
Forge Gradle hangs when using Sugarcane Mappings

### ISSUE THREAD

**Issue by Rover656** [noeppi-noeppi/ModGradle#14]
Whenever sugarcane mappings are used, Ender IO's builds stall infinitely until they are stopped and re-run, this breaks GitHub Actions. I'm providing 2 build logs from Actions to show you where this fails.

Using parchment: https://github.com/SleepyTrousers/EnderIO-Rewrite/runs/7889663799
Using sugarcane: https://github.com/SleepyTrousers/EnderIO-Rewrite/runs/7889774021

Happy to provide any more information if required :)

**Comment by noeppi-noeppi** [comment]
See https://github.com/MinecraftForge/ForgeGradle/issues/886

**Comment by noeppi-noeppi** [comment]
The reason, why the deadlock does not occur with parchment in most cases is that librarian only uses `MavenArtifactDownloader` very early in the method that resolves the mappings.

For downloading the actual mappings zip file, it has some custom logic that is used to support snapshots. However as SugarCane has no snapshots, it just uses `MavenArtifactDownloader` (which is also the fallback option in librarian).

**Comment by noeppi-noeppi** [comment]
Fixed in ForgeGradle
